language: node_js
node_js:
  - "16.14.2"
install:
    - npm install
script:
    - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
